#
# © 2026-present Godot Mobile Plugins (https://github.com/godot-mobile-plugins)
#

pluginNodeName=ConnectionState
pluginModuleName=connection_state
pluginPackage=org.godotengine.plugin.connectionstate
pluginVersion=1.2
